- id: "/"
  title: "PAPAP2017 - Particle and Astroparticle Physics Autumn Programme 2017"
  description: "The Particle & Astroparticle Physics Programme, now at its third edition, will bring 40 students to visit some of the most advanced research facilities in Europe, with a focus on astroparticle physics and one key mission: to foster enthusiasm in the minds of young physicists."
  keywords: "aisf associazione italiana studenti di fisica iaps astroparticle physics particle association students international programme event"
